---
title: Clasificación XYZ
author: Saúl Méndez
date: '2020-03-13'
slug: coeficiente-de-variación
categories:
  - Análisis descriptivo
tags:
  - Coeficiente de Variación
  - Administración de inventarios
subtitle: ''
summary: ''
authors: []
lastmod: '2020-03-13T14:10:34-06:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

# ¿Porqué utilizar el coeficiente de variación?

Es una forma de medir de forma estandarizada la volatilidad de distintas distribuciones. Nos permite hacer comparaciones de distintas variables haciendo uso de su valor medio y la desviación estándar.

## ¿Para qué nos puede servir?
Digamos que nuestra misión es determinar los niveles más adecuados de inventario y actualmente manejamos dos productos, el primer producto(p1) se registra en cajas y el segundo producto(p2) se maneja en sobres.

La forma más sencilla de atacar este problema es comprando el valor promedio. Esta estrategia funciona si tengo una demanda estable y poco variable. Este tipo de comportamiento, visto en un histograma se ve de la siguiente forma:
**INSERTAR GRÁFICO**

Recordemos que el valor al centro de la distribución es el promedio y que la mayoría de los valores observados se encuentran centrados muy cerca de este. El caso se complica cuando la distribución se comporta de forma más volátil, por lo que comprar el promedio puede significar un costo de oportunidad muy grande para nuestro ciente. Este tipo de situaciones se vería de la siguiente forma.

**INSERTAR GRÁFICO**

Para lograr una mejor del grado de volatilidad que se observa en la gráfica, utilizamos la desviación estándar. Esto con el objetivo de conocer cuantas unidades de separación al promedio puedo esperar. Con esto ya tenemos dos variables para describir el producto.

**INSERTAR TABLA**
¿Cual es más volatil?: intuitivamente podriamos haber pensado que la opción 2 es la más volatil(correcto)

En este caso, es muy facil identificar a ojo cual es la variable más volatil. ¿Qué harian en el caso de manejar 10,000 skus? Si seguimos usando el metodo del ojimetro, debemos prepararnos a una intensidad titánica de trabajo para identificar cuales son los más volatiles. Digamos que lo logramos y ahora queremos ordenarlos por nivel de volatilidad...en este caso ya no podemos hacer uso del trabajo manual y hasta aca llegariamos con nuestros esfuerzos.

## Introduciendo al Coeficiente de Variabilidad

La opción más sencilla y super facil de implementar es el calcular el Coeficiente de Variabilidad. 
Su definición es:` Desviación Estandar / Promedio`. 
El realizar esto nos permite quitarle las dimensiones a las medidas descriptivas (promedio, desviación estándar)

**INSERTAR ESCALA COMPARATIVA DEL VALOR DE COEFICIENTE PARA P1 Y P2**

# Estrategia simple de administración de la volatilidad

La estrategia mas sencilla que podemos realizar para clasificar la volatilidad, es generar rangos para tres tipos de distribución que podemos encontrar:

  * X -> CoV<=0.3
  * y -> 0.3<CoV<=0.6
  * z -> CoV>0.6
  
Luego, para cada una de estas clasificaciones definimos un nivel de servicio, el cual nos debe de ayudar a generar cual es el monto de inventario ideal.

## Nivel de servicio
Es la probabilidad con la que quiero asegurarme de cubrir la demanda durante un periodo de tiempo.
En estadística existe un concepto de la curva normal estándar, en donde el valor medio se encuentra centrado en 0 con una desviación estándar de +-1. Tambien tiene la caracteriztica que si sumamos el área de izquierda a derecha de la curva, esta suma exactamente 50% del área.

**COLOCAR IMAGEN DE CURVA DE PROBABILIDAD AL 50%**

Si a la media le sumamos una desviación estándar, el valor del área es del 84% aproximadamente. A este porcentaje del área es lo que conocemos como nivel de servicio.

**COLOCAR IMAGEN DE CURVA DE PROBABILIDAD AL 84%**


Bajo el enfoque que nos interesa, nosotros decidimos el nivel de servicio que queremos obtener, es decir con que nivel de confianza adicional le voy a agregar al promedio. Recordemos al determinar el nivel de servicio, estamos definiendo la cantidad de desviaciones estándar que le agregaremos al promedio.

Para el caso que estamos tratando, lo usual es usar los siguientes niveles de servicio.

  * x -> 98%(2.05)
  * y -> 85%(1.03)
  * z -> 65%(0.38) o 50%(0)

# Implementando la clasificación XYZ

  * Necesitamos la información mensual de venta de los U12M
  Para cada SKU
  * Calcular el promedio mensual de venta para cada SKU
  * Calcular la desviación estándar para cada SKU
  * Calcular el coeficiente de variación
  * Realizar la clasificación XYZ
  

  

